### ISSUE TITLE
Get events panics on `NOTICE` messages

### ISSUE THREAD

**Issue by thesimplekid** [0xtlt/nostr_rust#26]
https://github.com/0xtlt/nostr_rust/blob/109c369181ef928e45b2c8ca79908a2422fb875e/src/nostr_client.rs#L654

This panics when the relays (nostr-rs-relay) sends what I think is a `NOTICE` for example `["OK","29ef107b813f3cc7970dc959466025b96c548963d938f961937b78d30c9844b0",true,""]`

Not sure how it should be handled as Notices aren't well defined, bubble it up as an error, log it?

**Comment by 0xtlt** [comment]
ahhhh yup, will fix it

**Comment by 0xtlt** [comment]
Will be fixed in the 0.16.2 version which will be published in the following minutes :)
